// Data 118 prvků periodické tabulky.
// row/col odpovídají pozici v CSS gridu (řádky 1-7 hlavní tabulka, 9-10 f-blok).
// radioactive: true u prvků bez stabilního izotopu (Tc, Pm, Po a vše těžší).

const CATEGORIES = {
  alkali_metal:         { label: "Alkalické kovy",          color: "#fc6f6f" },
  alkaline_earth:       { label: "Kovy alkalických zemin",  color: "#fab560" },
  transition_metal:     { label: "Přechodné kovy",          color: "#f4d35e" },
  post_transition_metal:{ label: "Kovy bloku p",            color: "#92c9d6" },
  metalloid:            { label: "Polokovy",                color: "#82c8a0" },
  nonmetal:             { label: "Nekovy",                  color: "#5fb4e1" },
  halogen:              { label: "Halogeny",                color: "#b48ed1" },
  noble_gas:            { label: "Vzácné plyny",            color: "#d397d3" },
  lanthanide:           { label: "Lanthanoidy",             color: "#ff9eb5" },
  actinide:             { label: "Aktinoidy",               color: "#ff7eb1" },
  unknown:              { label: "Neznámé vlastnosti",      color: "#b8b8b8" },
};

const ELEMENTS = [
  { z:1,  symbol:"H",  nameCs:"Vodík",      nameEn:"Hydrogen",   category:"nonmetal",     period:1, group:1,  row:1, col:1,  mass:1.008,   radioactive:false,
    description:"Nejlehčí a nejhojnější prvek vesmíru, plynný za běžných podmínek. Tvoří hlavní palivo hvězd a je základem všech organických sloučenin. Na Zemi se vyskytuje téměř výhradně vázaný — především ve vodě." },
  { z:2,  symbol:"He", nameCs:"Helium",     nameEn:"Helium",     category:"noble_gas",    period:1, group:18, row:1, col:18, mass:4.0026,  radioactive:false,
    description:"Druhý nejlehčí prvek a vzácný plyn bez barvy a zápachu. Používá se v balonech, kapalný (–269 °C) k chlazení supravodičů a v MRI. Vzniká alfa-rozpadem těžkých radioaktivních prvků." },

  { z:3,  symbol:"Li", nameCs:"Lithium",    nameEn:"Lithium",    category:"alkali_metal", period:2, group:1,  row:2, col:1,  mass:6.94,    radioactive:false,
    description:"Nejlehčí kov, měkký a stříbřitě bílý. Klíčový pro Li-ion baterie v telefonech a elektromobilech. Sloučeniny lithia se používají v psychiatrii (bipolární porucha)." },
  { z:4,  symbol:"Be", nameCs:"Beryllium",  nameEn:"Beryllium",  category:"alkaline_earth", period:2, group:2, row:2, col:2,  mass:9.0122,  radioactive:false,
    description:"Lehký, tvrdý a toxický kov. Slitiny s mědí jsou pevné a nejiskřící — používají se v leteckém průmyslu a kosmonautice. Propouští rentgenové záření, takže slouží jako okénko v RTG trubicích." },
  { z:5,  symbol:"B",  nameCs:"Bor",        nameEn:"Boron",      category:"metalloid",    period:2, group:13, row:2, col:13, mass:10.81,   radioactive:false,
    description:"Tvrdý černý polokov. Sloučeniny (bórax, kyselina boritá) se používají ve sklářství (borosilikátové sklo Pyrex), pracích prostředcích a jako insekticidy. V jaderných reaktorech absorbuje neutrony." },
  { z:6,  symbol:"C",  nameCs:"Uhlík",      nameEn:"Carbon",     category:"nonmetal",     period:2, group:14, row:2, col:14, mass:12.011,  radioactive:false,
    description:"Základ veškerého života a organické chemie. Tvoří mnoho alotropů: diamant (nejtvrdší přírodní materiál), grafit, fullereny, grafen. Stojí v centru fosilních paliv a klimatu." },
  { z:7,  symbol:"N",  nameCs:"Dusík",      nameEn:"Nitrogen",   category:"nonmetal",     period:2, group:15, row:2, col:15, mass:14.007,  radioactive:false,
    description:"Tvoří 78 % zemské atmosféry. Je nezbytný pro proteiny a DNA. Kapalný dusík (–196 °C) slouží k chlazení a kryokonzervaci, sloučeniny k výrobě hnojiv a výbušnin." },
  { z:8,  symbol:"O",  nameCs:"Kyslík",     nameEn:"Oxygen",     category:"nonmetal",     period:2, group:16, row:2, col:16, mass:15.999,  radioactive:false,
    description:"Druhý nejhojnější plyn v atmosféře (21 %), nezbytný pro dýchání a hoření. Tvoří asi polovinu hmotnosti zemské kůry (oxidy, křemičitany). Tří-atomový kyslík je ozon, který chrání před UV." },
  { z:9,  symbol:"F",  nameCs:"Fluor",      nameEn:"Fluorine",   category:"halogen",      period:2, group:17, row:2, col:17, mass:18.998,  radioactive:false,
    description:"Nejreaktivnější prvek, světle žlutý plyn. Reaguje téměř se vším včetně skla a vzácných plynů. Používá se v zubních pastách (fluoridy), Teflonu a obohacování uranu (UF6)." },
  { z:10, symbol:"Ne", nameCs:"Neon",       nameEn:"Neon",       category:"noble_gas",    period:2, group:18, row:2, col:18, mass:20.180,  radioactive:false,
    description:"Inertní vzácný plyn, září oranžově-červeně ve výbojkách (neonové reklamy). Získává se destilací zkapalněného vzduchu. Chemicky netvoří žádné stabilní sloučeniny." },

  { z:11, symbol:"Na", nameCs:"Sodík",      nameEn:"Sodium",     category:"alkali_metal", period:3, group:1,  row:3, col:1,  mass:22.990,  radioactive:false,
    description:"Měkký stříbřitý kov, prudce reaguje s vodou. V přírodě jen ve sloučeninách (kuchyňská sůl NaCl). Pára ve výbojkách svítí typicky žlutě (sodíkové pouliční lampy)." },
  { z:12, symbol:"Mg", nameCs:"Hořčík",     nameEn:"Magnesium",  category:"alkaline_earth", period:3, group:2, row:3, col:2,  mass:24.305,  radioactive:false,
    description:"Lehký kov, hoří jasně bílým plamenem (pyrotechnika, blesková světla). Tvoří jádro chlorofylu, je tedy základem fotosyntézy. Slitiny se používají v letectví a notebookových šasi." },
  { z:13, symbol:"Al", nameCs:"Hliník",     nameEn:"Aluminium",  category:"post_transition_metal", period:3, group:13, row:3, col:13, mass:26.982,  radioactive:false,
    description:"Nejhojnější kov v zemské kůře. Lehký, korozivzdorný (díky pasivační vrstvě Al2O3), dobře vede teplo i elektřinu. Vyrábí se elektrolýzou bauxitu — energeticky velmi náročně." },
  { z:14, symbol:"Si", nameCs:"Křemík",     nameEn:"Silicon",    category:"metalloid",    period:3, group:14, row:3, col:14, mass:28.085,  radioactive:false,
    description:"Druhý nejhojnější prvek v zemské kůře (písek, křemen). Polovodičový základ veškeré moderní elektroniky a fotovoltaiky. Tvoří kostru sloučenin v keramice a sklářství." },
  { z:15, symbol:"P",  nameCs:"Fosfor",     nameEn:"Phosphorus", category:"nonmetal",     period:3, group:15, row:3, col:15, mass:30.974,  radioactive:false,
    description:"Existuje v alotropech: bílý (samozápalný a jedovatý), červený (zápalky) a černý. Klíčový pro DNA, ATP a kosti (fosforečnan vápenatý). Hlavní složka hnojiv." },
  { z:16, symbol:"S",  nameCs:"Síra",       nameEn:"Sulfur",     category:"nonmetal",     period:3, group:16, row:3, col:16, mass:32.06,   radioactive:false,
    description:"Žlutá pevná látka známá od pravěku. Páchne při hoření (SO2). Klíčová pro výrobu kyseliny sírové — nejvíce produkované chemikálie světa. Obsažena v aminokyselinách." },
  { z:17, symbol:"Cl", nameCs:"Chlor",      nameEn:"Chlorine",   category:"halogen",      period:3, group:17, row:3, col:17, mass:35.45,   radioactive:false,
    description:"Žlutozelený jedovatý plyn s ostrým zápachem. Používá se k dezinfekci pitné vody a bazénů, výrobě PVC a bělení. V první světové válce byl zneužit jako bojový plyn." },
  { z:18, symbol:"Ar", nameCs:"Argon",      nameEn:"Argon",      category:"noble_gas",    period:3, group:18, row:3, col:18, mass:39.948,  radioactive:false,
    description:"Třetí nejhojnější plyn v atmosféře (~1 %). Používá se jako ochranná atmosféra při svařování a v žárovkách (zabraňuje oxidaci wolframového vlákna). Chemicky téměř netečný." },

  { z:19, symbol:"K",  nameCs:"Draslík",    nameEn:"Potassium",  category:"alkali_metal", period:4, group:1,  row:4, col:1,  mass:39.098,  radioactive:false,
    description:"Měkký kov, prudce reaguje s vodou (až explozivně). Je nezbytný pro nervové vzruchy a srdeční činnost. Hlavní složka draselných hnojiv." },
  { z:20, symbol:"Ca", nameCs:"Vápník",     nameEn:"Calcium",    category:"alkaline_earth", period:4, group:2, row:4, col:2,  mass:40.078,  radioactive:false,
    description:"Pátý nejhojnější prvek v zemské kůře (vápenec, sádrovec). Stavební materiál kostí a zubů (hydroxyapatit). Cement, malta a sklo by bez něj neexistovaly." },
  { z:21, symbol:"Sc", nameCs:"Skandium",   nameEn:"Scandium",   category:"transition_metal", period:4, group:3, row:4, col:3, mass:44.956, radioactive:false,
    description:"Lehký, vzácný kov; jeho existenci předpověděl Mendělejev. Slitiny Al-Sc se používají v letectví a sportovním vybavení (rámy kol, baseballové pálky)." },
  { z:22, symbol:"Ti", nameCs:"Titan",      nameEn:"Titanium",   category:"transition_metal", period:4, group:4, row:4, col:4, mass:47.867, radioactive:false,
    description:"Lehký, pevný a velmi korozivzdorný kov. Použití: implantáty, letecké konstrukce, raketové motory. TiO2 je nejbělejší známé bílé barvivo." },
  { z:23, symbol:"V",  nameCs:"Vanad",      nameEn:"Vanadium",   category:"transition_metal", period:4, group:5, row:4, col:5, mass:50.942, radioactive:false,
    description:"Tvrdý kov, používá se k vytvrzování oceli (vanadová ocel, nářadí). Sloučeniny mají barevné oxidační stavy (+2 až +5). Vanadové průtokové baterie ukládají energii." },
  { z:24, symbol:"Cr", nameCs:"Chrom",      nameEn:"Chromium",   category:"transition_metal", period:4, group:6, row:4, col:6, mass:51.996, radioactive:false,
    description:"Lesklý, tvrdý kov, odolný proti korozi. Pochromování dává kovům zrcadlový lesk. Klíčový v nerezové oceli (≥10,5 % Cr). Cr⁶⁺ sloučeniny jsou karcinogenní." },
  { z:25, symbol:"Mn", nameCs:"Mangan",     nameEn:"Manganese",  category:"transition_metal", period:4, group:7, row:4, col:7, mass:54.938, radioactive:false,
    description:"Tvrdý a křehký kov. Klíčová přísada do oceli (až 90 % produkce manganu). Důležitý pro fotosyntézu (rozklad vody) a v alkalických bateriích (MnO2)." },
  { z:26, symbol:"Fe", nameCs:"Železo",     nameEn:"Iron",       category:"transition_metal", period:4, group:8, row:4, col:8, mass:55.845, radioactive:false,
    description:"Nejvíce používaný kov, hlavní složka oceli a litiny. Tvoří většinu zemského jádra. V hemoglobinu váže kyslík v krvi. Celá historická epocha (železná doba) je po něm pojmenována." },
  { z:27, symbol:"Co", nameCs:"Kobalt",     nameEn:"Cobalt",     category:"transition_metal", period:4, group:9, row:4, col:9, mass:58.933, radioactive:false,
    description:"Lesklý kov s magnetickými vlastnostmi. Používá se v Li-ion bateriích, slitinách pro nástroje a magnetech. Vitamin B12 obsahuje kobalt." },
  { z:28, symbol:"Ni", nameCs:"Nikl",       nameEn:"Nickel",     category:"transition_metal", period:4, group:10, row:4, col:10, mass:58.693, radioactive:false,
    description:"Stříbřitě lesklý, tažný a korozivzdorný kov. Klíčový v nerezové oceli, mincích a NiMH/Ni-Cd bateriích. Hlavní složka jádra Země vedle železa." },
  { z:29, symbol:"Cu", nameCs:"Měď",        nameEn:"Copper",     category:"transition_metal", period:4, group:11, row:4, col:11, mass:63.546, radioactive:false,
    description:"Vynikající vodič elektřiny i tepla, červeně zlatý kov známý od pravěku. Slitiny: bronz (s cínem), mosaz (se zinkem). Používá se v elektroinstalacích, vodičích a střechách." },
  { z:30, symbol:"Zn", nameCs:"Zinek",      nameEn:"Zinc",       category:"transition_metal", period:4, group:12, row:4, col:12, mass:65.38, radioactive:false,
    description:"Modrobílý kov, používá se k pozinkování oceli (ochrana proti korozi). V mosazi, suchých článcích a léčivech. Stopový prvek nezbytný pro imunitu." },
  { z:31, symbol:"Ga", nameCs:"Gallium",    nameEn:"Gallium",    category:"post_transition_metal", period:4, group:13, row:4, col:13, mass:69.723, radioactive:false,
    description:"Měkký kov, taje již při 30 °C — roztaje v dlani. GaAs a GaN jsou důležité polovodiče (LED, lasery, vysokofrekvenční elektronika 5G)." },
  { z:32, symbol:"Ge", nameCs:"Germanium",  nameEn:"Germanium",  category:"metalloid",    period:4, group:14, row:4, col:14, mass:72.630, radioactive:false,
    description:"Šedo-bílý polokov, historicky první polovodič v tranzistorech (1947). Dnes se používá v optice (infračervené čočky, optická vlákna) a solárních článcích." },
  { z:33, symbol:"As", nameCs:"Arsen",      nameEn:"Arsenic",    category:"metalloid",    period:4, group:15, row:4, col:15, mass:74.922, radioactive:false,
    description:"Šedý polokov, sloučeniny silně jedovaté — historicky oblíbený jed. Používá se v polovodičích (GaAs), pesticidech a slitinách. Otrava dlouhodobou expozicí způsobuje rakovinu." },
  { z:34, symbol:"Se", nameCs:"Selen",      nameEn:"Selenium",   category:"nonmetal",     period:4, group:16, row:4, col:16, mass:78.971, radioactive:false,
    description:"Polokov-nekov; jeho elektrický odpor klesá s osvětlením (fotorezistor, kopírky). Stopový prvek nezbytný pro enzymy. Toxický v nadbytku." },
  { z:35, symbol:"Br", nameCs:"Brom",       nameEn:"Bromine",    category:"halogen",      period:4, group:17, row:4, col:17, mass:79.904, radioactive:false,
    description:"Jediný kapalný nekov za pokojové teploty (rudohnědá těkavá kapalina). Používá se v retardérech hoření, dezinfekci a fotografii (AgBr). Páry leptají a jsou toxické." },
  { z:36, symbol:"Kr", nameCs:"Krypton",    nameEn:"Krypton",    category:"noble_gas",    period:4, group:18, row:4, col:18, mass:83.798, radioactive:false,
    description:"Vzácný plyn, plní úsporné žárovky a výbojky (intenzivní bílé světlo). Krypton-85 (radioaktivní) se uvolňuje z jaderných reaktorů. Definoval délku metru 1960–1983." },

  { z:37, symbol:"Rb", nameCs:"Rubidium",   nameEn:"Rubidium",   category:"alkali_metal", period:5, group:1,  row:5, col:1,  mass:85.468, radioactive:false,
    description:"Měkký stříbřitý alkalický kov, prudce reaguje s vodou (až výbušně). Používá se v atomových hodinách a fotokatodách. V přírodě stopově v lithných minerálech." },
  { z:38, symbol:"Sr", nameCs:"Stroncium",  nameEn:"Strontium",  category:"alkaline_earth", period:5, group:2, row:5, col:2,  mass:87.62, radioactive:false,
    description:"Kov podobný vápníku. Soli barví plamen jasně červeně (ohňostroje, světlice). Stroncium-90 z jaderných výbuchů se ukládá v kostech místo vápníku." },
  { z:39, symbol:"Y",  nameCs:"Yttrium",    nameEn:"Yttrium",    category:"transition_metal", period:5, group:3, row:5, col:3, mass:88.906, radioactive:false,
    description:"Stříbřitý vzácný kov, klíčový pro YAG lasery, vysokoteplotní supravodiče (YBCO) a červené luminofory v LED a starých CRT obrazovkách." },
  { z:40, symbol:"Zr", nameCs:"Zirkonium",  nameEn:"Zirconium",  category:"transition_metal", period:5, group:4, row:5, col:4, mass:91.224, radioactive:false,
    description:"Korozivzdorný kov s nízkou absorpcí neutronů — používá se na obaly palivových tyčí v jaderných reaktorech. ZrO2 (zirkon) je oblíbený šperkařský kámen." },
  { z:41, symbol:"Nb", nameCs:"Niob",       nameEn:"Niobium",    category:"transition_metal", period:5, group:5, row:5, col:5, mass:92.906, radioactive:false,
    description:"Měkký šedý kov; supravodivý při nízkých teplotách (slitiny Nb3Sn v MRI a urychlovačích). Používá se v hypoalergenních špercích a piercingu." },
  { z:42, symbol:"Mo", nameCs:"Molybden",   nameEn:"Molybdenum", category:"transition_metal", period:5, group:6, row:5, col:6, mass:95.95, radioactive:false,
    description:"Tvrdý kov s velmi vysokou teplotou tání (2623 °C). Používá se v ocelích pro nástroje a turbíny, MoS2 jako mazivo." },
  { z:43, symbol:"Tc", nameCs:"Technecium", nameEn:"Technetium", category:"transition_metal", period:5, group:7, row:5, col:7, mass:98, radioactive:true,
    description:"První uměle vyrobený prvek (1937). Nemá stabilní izotop. Tc-99m se používá v nukleární medicíně k zobrazování (~30 milionů vyšetření ročně)." },
  { z:44, symbol:"Ru", nameCs:"Ruthenium",  nameEn:"Ruthenium",  category:"transition_metal", period:5, group:8, row:5, col:8, mass:101.07, radioactive:false,
    description:"Tvrdý platinový kov, výborný katalyzátor (Haberův-Boschův proces, palivové články). V tvrdých discích zvyšoval hustotu zápisu (PMR)." },
  { z:45, symbol:"Rh", nameCs:"Rhodium",    nameEn:"Rhodium",    category:"transition_metal", period:5, group:9, row:5, col:9, mass:102.91, radioactive:false,
    description:"Vzácný stříbřitě bílý platinový kov. Hlavní použití: katalyzátory v automobilech (redukce NOx). Patří k nejdražším kovům světa." },
  { z:46, symbol:"Pd", nameCs:"Palladium",  nameEn:"Palladium",  category:"transition_metal", period:5, group:10, row:5, col:10, mass:106.42, radioactive:false,
    description:"Vzácný platinový kov; pohlcuje až 900× svůj objem vodíku (paliva. články). Používá se v autokatalyzátorech a elektronice. V roce 2020 cenou předehnal zlato." },
  { z:47, symbol:"Ag", nameCs:"Stříbro",    nameEn:"Silver",     category:"transition_metal", period:5, group:11, row:5, col:11, mass:107.87, radioactive:false,
    description:"Nejlepší vodič elektřiny a tepla mezi všemi kovy. Antibakteriální (zdravotnictví). Šperky, mince, fotografie (AgBr), zrcadla. V přírodě se vyskytuje i ryzí." },
  { z:48, symbol:"Cd", nameCs:"Kadmium",    nameEn:"Cadmium",    category:"transition_metal", period:5, group:12, row:5, col:12, mass:112.41, radioactive:false,
    description:"Měkký toxický kov. Použití: NiCd baterie, pigmenty (kadmiová žluť), galvanické pokovování. V EU silně omezeno kvůli toxicitě a karcinogenitě." },
  { z:49, symbol:"In", nameCs:"Indium",     nameEn:"Indium",     category:"post_transition_metal", period:5, group:13, row:5, col:13, mass:114.82, radioactive:false,
    description:"Měkký stříbřitě bílý kov. ITO (oxid india a cínu) je transparentní vodič — podstata dotykových obrazovek a LCD displejů." },
  { z:50, symbol:"Sn", nameCs:"Cín",        nameEn:"Tin",        category:"post_transition_metal", period:5, group:14, row:5, col:14, mass:118.71, radioactive:false,
    description:"Stříbřitě bílý měkký kov, známý od pravěku (bronz = Cu+Sn). Plechovky, pájky (Sn-Pb, dnes bez Pb), polevy. Pod –13 °C přechází na šedý prášek („cínový mor“)." },
  { z:51, symbol:"Sb", nameCs:"Antimon",    nameEn:"Antimony",   category:"metalloid",    period:5, group:15, row:5, col:15, mass:121.76, radioactive:false,
    description:"Stříbřitý křehký polokov. Používá se v retardérech hoření, slitinách (olověné akumulátory) a polovodičích. Sloučeniny jsou toxické." },
  { z:52, symbol:"Te", nameCs:"Tellur",     nameEn:"Tellurium",  category:"metalloid",    period:5, group:16, row:5, col:16, mass:127.60, radioactive:false,
    description:"Vzácný stříbřitě bílý polokov, sloučeniny páchnou jako česnek (i v dechu). Použití: tenkovrstvé solární články CdTe, slitiny pro odlévání, Blu-ray média." },
  { z:53, symbol:"I",  nameCs:"Jod",        nameEn:"Iodine",     category:"halogen",      period:5, group:17, row:5, col:17, mass:126.90, radioactive:false,
    description:"Tmavě fialové krystaly, sublimují na fialové páry. Nezbytný pro štítnou žlázu (jodizovaná sůl). Roztoky se používají k dezinfekci ran." },
  { z:54, symbol:"Xe", nameCs:"Xenon",      nameEn:"Xenon",      category:"noble_gas",    period:5, group:18, row:5, col:18, mass:131.29, radioactive:false,
    description:"Vzácný plyn použitý ve výbojkách (xenonové automobilové světlomety, blesky). V medicíně jako anestetikum. Tvoří první známé sloučeniny vzácných plynů (XeF2, XeF4)." },

  { z:55, symbol:"Cs", nameCs:"Cesium",     nameEn:"Caesium",    category:"alkali_metal", period:6, group:1,  row:6, col:1,  mass:132.91, radioactive:false,
    description:"Zlatavý měkký kov, taje při 28 °C. Nejreaktivnější stabilní kov — exploduje na vzduchu i s ledovou vodou. Cs-133 definuje sekundu (atomové hodiny)." },
  { z:56, symbol:"Ba", nameCs:"Baryum",     nameEn:"Barium",     category:"alkaline_earth", period:6, group:2, row:6, col:2,  mass:137.33, radioactive:false,
    description:"Měkký kov; sloučeniny barví plamen zeleně (ohňostroje). BaSO4 (síran barnatý) se polyká před RTG vyšetřením střev — neprostupný pro záření." },

  { z:72, symbol:"Hf", nameCs:"Hafnium",    nameEn:"Hafnium",    category:"transition_metal", period:6, group:4, row:6, col:4, mass:178.49, radioactive:false,
    description:"Stříbřitý lesklý kov, chemicky téměř totožný se zirkoniem. Silně absorbuje neutrony — řídicí tyče v jaderných reaktorech. HfO2 v moderních CPU jako gate dielectric." },
  { z:73, symbol:"Ta", nameCs:"Tantal",     nameEn:"Tantalum",   category:"transition_metal", period:6, group:5, row:6, col:5, mass:180.95, radioactive:false,
    description:"Tvrdý odolný kov, vysoce korozivzdorný (i vůči kyselinám). Tantalové kondenzátory v telefonech a elektronice. Inertní vůči tělním tekutinám — chirurgické implantáty." },
  { z:74, symbol:"W",  nameCs:"Wolfram",    nameEn:"Tungsten",   category:"transition_metal", period:6, group:6, row:6, col:6, mass:183.84, radioactive:false,
    description:"Nejvyšší teplota tání ze všech kovů (3422 °C). Vlákna v žárovkách, řezné nástroje (karbidy), pancéřové projektily. Hustota srovnatelná se zlatem." },
  { z:75, symbol:"Re", nameCs:"Rhenium",    nameEn:"Rhenium",    category:"transition_metal", period:6, group:7, row:6, col:7, mass:186.21, radioactive:false,
    description:"Velmi vzácný kov s velmi vysokou teplotou tání. Používá se ve slitinách pro lopatky tryskových motorů a jako katalyzátor při výrobě bezolovnatého benzínu." },
  { z:76, symbol:"Os", nameCs:"Osmium",     nameEn:"Osmium",     category:"transition_metal", period:6, group:8, row:6, col:8, mass:190.23, radioactive:false,
    description:"Nejhustší přírodní prvek (22,59 g/cm³). Modrošedý platinový kov. Slitiny pro hroty plnicích per, elektrické kontakty. OsO4 je velmi toxický." },
  { z:77, symbol:"Ir", nameCs:"Iridium",    nameEn:"Iridium",    category:"transition_metal", period:6, group:9, row:6, col:9, mass:192.22, radioactive:false,
    description:"Druhý nejhustší prvek, mimořádně korozivzdorný. Vzácný v zemské kůře, ale hojný v meteoritech — vrstva v K-Pg hranici je důkazem dopadu, který vyhubil dinosaury." },
  { z:78, symbol:"Pt", nameCs:"Platina",    nameEn:"Platinum",   category:"transition_metal", period:6, group:10, row:6, col:10, mass:195.08, radioactive:false,
    description:"Lesklý drahý kov, mimořádně korozivzdorný. Nejdůležitější použití: katalyzátory (autokatalyzátory, palivové články, výroba kyseliny dusičné). Šperky a investiční slitky." },
  { z:79, symbol:"Au", nameCs:"Zlato",      nameEn:"Gold",       category:"transition_metal", period:6, group:11, row:6, col:11, mass:196.97, radioactive:false,
    description:"Žlutý lesklý ušlechtilý kov, neoxiduje a nereaguje s kyselinami (kromě lučavky královské). Rezerva centrálních bank, šperky, kontakty v elektronice (zlacení)." },
  { z:80, symbol:"Hg", nameCs:"Rtuť",       nameEn:"Mercury",    category:"transition_metal", period:6, group:12, row:6, col:12, mass:200.59, radioactive:false,
    description:"Jediný kov, který je při pokojové teplotě kapalný. Stříbřitě lesklý, vysoce toxický (zejména páry a organortuťnaté sloučeniny). Tradičně teploměry, dnes z velké části vyřazena." },
  { z:81, symbol:"Tl", nameCs:"Thallium",   nameEn:"Thallium",   category:"post_transition_metal", period:6, group:13, row:6, col:13, mass:204.38, radioactive:false,
    description:"Měkký šedý kov, extrémně toxický (bez chuti, bez zápachu — historický „jed travičů“). Dříve insekticidy a jed na hlodavce. Dnes specializované optické skleněné čočky." },
  { z:82, symbol:"Pb", nameCs:"Olovo",      nameEn:"Lead",       category:"post_transition_metal", period:6, group:14, row:6, col:14, mass:207.2,  radioactive:false,
    description:"Těžký, měkký, šedý toxický kov, známý odpradávna. Olověné akumulátory (autobaterie), stínění před RTG zářením, pájky. V benzínu zakázáno (neurotoxin)." },
  { z:83, symbol:"Bi", nameCs:"Bismut",     nameEn:"Bismuth",    category:"post_transition_metal", period:6, group:15, row:6, col:15, mass:208.98, radioactive:false,
    description:"Křehký narůžovělý kov. Krystaly tvoří duhové geometrické tvary. Náhrada za olovo (broky, pájky), v lécích na zažívání (pepto-bismol). Technicky velmi slabě radioaktivní." },
  { z:84, symbol:"Po", nameCs:"Polonium",   nameEn:"Polonium",   category:"post_transition_metal", period:6, group:16, row:6, col:16, mass:209, radioactive:true,
    description:"Vysoce radioaktivní kov, objeven Marií Curie a pojmenován po Polsku. Alfa zářič — milion krát toxičtější než kyanid. Použit při vraždě Litviněnka (2006)." },
  { z:85, symbol:"At", nameCs:"Astat",      nameEn:"Astatine",   category:"halogen",      period:6, group:17, row:6, col:17, mass:210, radioactive:true,
    description:"Nejvzácnější přírodní prvek — v zemské kůře jen pár gramů. Všechny izotopy radioaktivní s krátkým poločasem rozpadu. Zkoumán pro cílenou alfa-terapii rakoviny." },
  { z:86, symbol:"Rn", nameCs:"Radon",      nameEn:"Radon",      category:"noble_gas",    period:6, group:18, row:6, col:18, mass:222, radioactive:true,
    description:"Radioaktivní vzácný plyn vznikající rozpadem radia v půdě a horninách. Hromadí se v sklepích — druhá nejčastější příčina rakoviny plic po kouření." },

  { z:87, symbol:"Fr", nameCs:"Francium",   nameEn:"Francium",   category:"alkali_metal", period:7, group:1,  row:7, col:1,  mass:223, radioactive:true,
    description:"Druhý nejvzácnější přírodní prvek. Všechny izotopy silně radioaktivní (poločas Fr-223 jen 22 minut). V přírodě stopově v uranových rudách." },
  { z:88, symbol:"Ra", nameCs:"Radium",     nameEn:"Radium",     category:"alkaline_earth", period:7, group:2, row:7, col:2,  mass:226, radioactive:true,
    description:"Stříbřitě bílý radioaktivní kov objevený Curieovými. Historicky se používal v luminiscenčních barvách (hodinky, ciferníky) — dělnice „Radium Girls“ na něj umíraly." },

  { z:104, symbol:"Rf", nameCs:"Rutherfordium", nameEn:"Rutherfordium", category:"transition_metal", period:7, group:4, row:7, col:4, mass:267, radioactive:true,
    description:"Supertěžký uměle vyrobený prvek. Pojmenován po Ernestu Rutherfordovi. Všechny izotopy mají velmi krátký poločas rozpadu (sekundy až minuty)." },
  { z:105, symbol:"Db", nameCs:"Dubnium",      nameEn:"Dubnium",      category:"transition_metal", period:7, group:5, row:7, col:5, mass:268, radioactive:true,
    description:"Supertěžký uměle vyrobený prvek, pojmenován po městě Dubna v Rusku (jaderné výzkumné centrum). Existuje jen v laboratoři." },
  { z:106, symbol:"Sg", nameCs:"Seaborgium",   nameEn:"Seaborgium",   category:"transition_metal", period:7, group:6, row:7, col:6, mass:269, radioactive:true,
    description:"Pojmenován po Glennu Seaborgovi (objevitel mnoha aktinoidů). Vzniká bombardováním kalifornia neony. Studuje se chemické chování supertěžkých prvků." },
  { z:107, symbol:"Bh", nameCs:"Bohrium",     nameEn:"Bohrium",      category:"transition_metal", period:7, group:7, row:7, col:7, mass:270, radioactive:true,
    description:"Supertěžký uměle vyrobený prvek pojmenovaný po Nielsi Bohrovi. Velmi krátký poločas rozpadu, vyrábí se v urychlovačích po atomech." },
  { z:108, symbol:"Hs", nameCs:"Hassium",    nameEn:"Hassium",      category:"transition_metal", period:7, group:8, row:7, col:8, mass:269, radioactive:true,
    description:"Pojmenován podle latinského Hassia (Hesensko, Německo). První supertěžký prvek, jehož chemie byla studována (chová se jako osmium)." },
  { z:109, symbol:"Mt", nameCs:"Meitnerium", nameEn:"Meitnerium",   category:"unknown", period:7, group:9, row:7, col:9, mass:278, radioactive:true,
    description:"Pojmenován po Lise Meitnerové (spoluobjevitelka jaderného štěpení). Vzniká fúzí bismutu a železa. Jen několik atomů kdy vyrobeno." },
  { z:110, symbol:"Ds", nameCs:"Darmstadtium", nameEn:"Darmstadtium", category:"unknown", period:7, group:10, row:7, col:10, mass:281, radioactive:true,
    description:"Supertěžký prvek, pojmenován po městě Darmstadt v Německu (GSI laboratoř). Poprvé vyroben 1994 fúzí olova a niklu." },
  { z:111, symbol:"Rg", nameCs:"Roentgenium", nameEn:"Roentgenium", category:"unknown", period:7, group:11, row:7, col:11, mass:282, radioactive:true,
    description:"Pojmenován po W. C. Röntgenovi (objeviteli RTG záření). Předpokládá se chemické chování podobné zlatu. Krátký poločas rozpadu." },
  { z:112, symbol:"Cn", nameCs:"Kopernicium", nameEn:"Copernicium", category:"transition_metal", period:7, group:12, row:7, col:12, mass:285, radioactive:true,
    description:"Pojmenován po Mikuláši Koperníkovi. Předpokládá se, že je za běžných podmínek kapalný — třetí kapalný kov po rtuti a galiu (téměř)." },
  { z:113, symbol:"Nh", nameCs:"Nihonium",   nameEn:"Nihonium",     category:"unknown", period:7, group:13, row:7, col:13, mass:286, radioactive:true,
    description:"První prvek objevený v Asii — japonským týmem v institutu RIKEN. Jméno z japonského „Nihon“ (Japonsko)." },
  { z:114, symbol:"Fl", nameCs:"Flerovium",  nameEn:"Flerovium",   category:"unknown", period:7, group:14, row:7, col:14, mass:289, radioactive:true,
    description:"Pojmenován po Georgiji Fleorovi (sovětský fyzik). Nachází se na okraji předpokládaného „ostrova stability“ supertěžkých prvků." },
  { z:115, symbol:"Mc", nameCs:"Moscovium",  nameEn:"Moscovium",   category:"unknown", period:7, group:15, row:7, col:15, mass:290, radioactive:true,
    description:"Supertěžký prvek vyrobený 2003 v Dubně. Jméno podle Moskevské oblasti. Velmi krátký poločas rozpadu (zlomky sekundy)." },
  { z:116, symbol:"Lv", nameCs:"Livermorium", nameEn:"Livermorium", category:"unknown", period:7, group:16, row:7, col:16, mass:293, radioactive:true,
    description:"Pojmenován po Lawrenceově laboratoři Livermore v Kalifornii. Existuje jen v laboratoři, vyroben fúzí curia a vápníku." },
  { z:117, symbol:"Ts", nameCs:"Tennessin",  nameEn:"Tennessine",  category:"unknown", period:7, group:17, row:7, col:17, mass:294, radioactive:true,
    description:"Pojmenován po státu Tennessee (Oak Ridge National Laboratory). Patří mezi halogeny, ale chemicky se patrně chová odlišně." },
  { z:118, symbol:"Og", nameCs:"Oganesson",  nameEn:"Oganesson",   category:"noble_gas", period:7, group:18, row:7, col:18, mass:294, radioactive:true,
    description:"Nejtěžší známý prvek (Z=118). Pojmenován po žijícím vědci Juriji Oganesianovi. Patří mezi vzácné plyny, ale teoreticky by mohl být pevnou látkou." },

  // Lanthanoidy (f-blok, řádek 9 v gridu)
  { z:57, symbol:"La", nameCs:"Lanthan",     nameEn:"Lanthanum",    category:"lanthanide", period:6, group:null, row:9, col:3,  mass:138.91, radioactive:false,
    description:"Stříbřitě bílý měkký kov, první ze skupiny lanthanoidů. Sloučeniny v optických sklech (objektivy fotoaparátů), NiMH bateriích (hybridní auta)." },
  { z:58, symbol:"Ce", nameCs:"Cer",         nameEn:"Cerium",       category:"lanthanide", period:6, group:null, row:9, col:4,  mass:140.12, radioactive:false,
    description:"Nejhojnější lanthanoid v zemské kůře. Používá se v autokatalyzátorech, leštících práškách na sklo, samočisticí troubách (CeO2). Zápalný kámen do zapalovačů (slitina ferrocer)." },
  { z:59, symbol:"Pr", nameCs:"Praseodym",   nameEn:"Praseodymium", category:"lanthanide", period:6, group:null, row:9, col:5,  mass:140.91, radioactive:false,
    description:"Stříbřitý kov, sloučeniny zelené. Spolu s neodymem v silných magnetech a barvení skla a smaltů na žluto-zeleno (praseodymové sklo)." },
  { z:60, symbol:"Nd", nameCs:"Neodym",      nameEn:"Neodymium",    category:"lanthanide", period:6, group:null, row:9, col:6,  mass:144.24, radioactive:false,
    description:"Nejsilnější permanentní magnety světa (NdFeB) — pevné disky, motory elektromobilů, větrné turbíny, sluchátka. Nepostradatelný pro moderní techniku." },
  { z:61, symbol:"Pm", nameCs:"Promethium",  nameEn:"Promethium",   category:"lanthanide", period:6, group:null, row:9, col:7,  mass:145, radioactive:true,
    description:"Jediný radioaktivní lanthanoid, v přírodě jen stopově. Používá se v luminiscenčních barvách a jaderných bateriích (kosmonautika, kardiostimulátory dříve)." },
  { z:62, symbol:"Sm", nameCs:"Samarium",    nameEn:"Samarium",     category:"lanthanide", period:6, group:null, row:9, col:8,  mass:150.36, radioactive:false,
    description:"Magnety SmCo (samarium-kobalt) odolávají vysokým teplotám — použití ve vojenské technice, leteckých motorech a sluchátkách." },
  { z:63, symbol:"Eu", nameCs:"Europium",    nameEn:"Europium",     category:"lanthanide", period:6, group:null, row:9, col:9,  mass:151.96, radioactive:false,
    description:"Nejreaktivnější lanthanoid. Klíčový luminofor — červené body v LED a starých CRT obrazovkách, ochranné značky na euro-bankovkách (svítí v UV)." },
  { z:64, symbol:"Gd", nameCs:"Gadolinium",  nameEn:"Gadolinium",   category:"lanthanide", period:6, group:null, row:9, col:10, mass:157.25, radioactive:false,
    description:"Silně paramagnetický kov, používá se jako kontrastní látka při MRI vyšetřeních. Pohlcuje neutrony — jaderné reaktory (řídicí tyče)." },
  { z:65, symbol:"Tb", nameCs:"Terbium",     nameEn:"Terbium",      category:"lanthanide", period:6, group:null, row:9, col:11, mass:158.93, radioactive:false,
    description:"Vzácný kov; zelený luminofor v LED a obrazovkách. Slitiny s dysprosiem mění tvar v magnetickém poli (sonary, aktuátory)." },
  { z:66, symbol:"Dy", nameCs:"Dysprosium",  nameEn:"Dysprosium",   category:"lanthanide", period:6, group:null, row:9, col:12, mass:162.50, radioactive:false,
    description:"Klíčová přísada do magnetů NdFeB pro vysoké teploty (motory elektromobilů, větrné turbíny). Strategicky důležitá vzácná zemina." },
  { z:67, symbol:"Ho", nameCs:"Holmium",     nameEn:"Holmium",      category:"lanthanide", period:6, group:null, row:9, col:13, mass:164.93, radioactive:false,
    description:"Má nejvyšší magnetickou permeabilitu ze všech prvků. Holmium-YAG lasery se používají v lékařství (urologie, ledvinové kameny)." },
  { z:68, symbol:"Er", nameCs:"Erbium",      nameEn:"Erbium",       category:"lanthanide", period:6, group:null, row:9, col:14, mass:167.26, radioactive:false,
    description:"Erbium-doped fiber zesilovače (EDFA) zesilují signál v optických vláknech — páteř internetu. Růžový pigment ve sklech a porcelánu." },
  { z:69, symbol:"Tm", nameCs:"Thulium",     nameEn:"Thulium",      category:"lanthanide", period:6, group:null, row:9, col:15, mass:168.93, radioactive:false,
    description:"Nejvzácnější stabilní lanthanoid. Tm-170 (radioaktivní) jako přenosný RTG zdroj v polních podmínkách. Lasery v medicíně." },
  { z:70, symbol:"Yb", nameCs:"Ytterbium",   nameEn:"Ytterbium",    category:"lanthanide", period:6, group:null, row:9, col:16, mass:173.05, radioactive:false,
    description:"Stříbřitý kov; využívá se ve vysoce výkonných pulzních laserech a v atomových hodinách nové generace (přesnost lepší než cesium)." },
  { z:71, symbol:"Lu", nameCs:"Lutecium",    nameEn:"Lutetium",     category:"lanthanide", period:6, group:null, row:9, col:17, mass:174.97, radioactive:false,
    description:"Poslední a nejtvrdší lanthanoid. Nejdražší vzácná zemina. Použití: PET skenery (LSO scintilátory), katalyzátory, datace minerálů." },

  // Aktinoidy (f-blok, řádek 10 v gridu)
  { z:89, symbol:"Ac",  nameCs:"Aktinium",     nameEn:"Actinium",     category:"actinide", period:7, group:null, row:10, col:3,  mass:227, radioactive:true,
    description:"Stříbřitě bílý radioaktivní kov, září v temnu modrobíle. Používán ve výzkumu cílené alfa-terapie nádorů (Ac-225)." },
  { z:90, symbol:"Th",  nameCs:"Thorium",      nameEn:"Thorium",      category:"actinide", period:7, group:null, row:10, col:4,  mass:232.04, radioactive:true,
    description:"Mírně radioaktivní kov, hojnější než uran. Potenciální palivo do thoriových reaktorů (bezpečnější, méně odpadu). Dříve v plynových punčoškách." },
  { z:91, symbol:"Pa",  nameCs:"Protaktinium", nameEn:"Protactinium", category:"actinide", period:7, group:null, row:10, col:5,  mass:231.04, radioactive:true,
    description:"Vzácný a vysoce radioaktivní stříbřitý kov. Používá se prakticky jen ve výzkumu — radiochemické datování oceánských sedimentů." },
  { z:92, symbol:"U",   nameCs:"Uran",         nameEn:"Uranium",      category:"actinide", period:7, group:null, row:10, col:6,  mass:238.03, radioactive:true,
    description:"Nejtěžší přírodní prvek. Štěpí se v jaderných reaktorech (U-235) a atomových bombách. Ochuzený uran (U-238) jako pancíř a v projektilech." },
  { z:93, symbol:"Np",  nameCs:"Neptunium",    nameEn:"Neptunium",    category:"actinide", period:7, group:null, row:10, col:7,  mass:237, radioactive:true,
    description:"První transuranový prvek vyrobený lidmi (1940). Vzniká v reaktorech jako vedlejší produkt. Použití: detektory neutronů." },
  { z:94, symbol:"Pu",  nameCs:"Plutonium",    nameEn:"Plutonium",    category:"actinide", period:7, group:null, row:10, col:8,  mass:244, radioactive:true,
    description:"Štěpný kov, palivo jaderných zbraní (Nagasaki) i reaktorů (MOX palivo). Pu-238 napájí kosmické sondy (Voyager, Curiosity)." },
  { z:95, symbol:"Am",  nameCs:"Americium",    nameEn:"Americium",    category:"actinide", period:7, group:null, row:10, col:9,  mass:243, radioactive:true,
    description:"Jediný transuran v běžném domácím použití — Am-241 v kouřových detektorech ionizuje vzduch a detekuje kouř." },
  { z:96, symbol:"Cm",  nameCs:"Curium",       nameEn:"Curium",       category:"actinide", period:7, group:null, row:10, col:10, mass:247, radioactive:true,
    description:"Pojmenován po manželech Curieových. Silně alfa-radioaktivní, září v temnu (samozářivost). Slouží v rentgenových spektrometrech kosmických sond." },
  { z:97, symbol:"Bk",  nameCs:"Berkelium",    nameEn:"Berkelium",    category:"actinide", period:7, group:null, row:10, col:11, mass:247, radioactive:true,
    description:"Vyroben 1949 v Berkeley. Existuje jen v gramových množstvích. Použit při syntéze tennessinu (prvku 117)." },
  { z:98, symbol:"Cf",  nameCs:"Kalifornium",  nameEn:"Californium",  category:"actinide", period:7, group:null, row:10, col:12, mass:251, radioactive:true,
    description:"Silný neutronový zdroj — používá se v lékařské radioterapii a k zahájení reakce v jaderných reaktorech. Jeden z nejdražších prvků světa." },
  { z:99, symbol:"Es",  nameCs:"Einsteinium",  nameEn:"Einsteinium",  category:"actinide", period:7, group:null, row:10, col:13, mass:252, radioactive:true,
    description:"Objeven v troskách první vodíkové bomby (Ivy Mike, 1952). Pojmenován po Einsteinovi. Existuje pouze v laboratoři." },
  { z:100, symbol:"Fm", nameCs:"Fermium",      nameEn:"Fermium",      category:"actinide", period:7, group:null, row:10, col:14, mass:257, radioactive:true,
    description:"Pojmenován po Enrico Fermim. Nejtěžší prvek vyrobitelný neutronovým ozařováním v reaktorech — těžší jen ostřelováním ionty." },
  { z:101, symbol:"Md", nameCs:"Mendelevium",  nameEn:"Mendelevium",  category:"actinide", period:7, group:null, row:10, col:15, mass:258, radioactive:true,
    description:"Pojmenován po D. I. Mendělejevovi. Vyrobeno jen několik atomů. Nemá praktické použití." },
  { z:102, symbol:"No", nameCs:"Nobelium",     nameEn:"Nobelium",     category:"actinide", period:7, group:null, row:10, col:16, mass:259, radioactive:true,
    description:"Pojmenován po Alfredu Nobelovi. Velmi krátký poločas rozpadu (minuty). Existuje pouze ve výzkumu." },
  { z:103, symbol:"Lr", nameCs:"Lawrencium",   nameEn:"Lawrencium",   category:"actinide", period:7, group:null, row:10, col:17, mass:266, radioactive:true,
    description:"Poslední aktinoid, pojmenován po E. Lawrencovi (vynálezce cyklotronu). Existuje pouze ve výzkumu — vyrobeno méně než 100 atomů." },
];

// Ukazatele (placeholdery) na pozici (6,3) a (7,3) v hlavní tabulce — odkazy na f-blok
const PLACEHOLDERS = [
  { row:6, col:3, label:"57–71",  target:"Lanthanoidy" },
  { row:7, col:3, label:"89–103", target:"Aktinoidy" },
];

ELEMENTS.sort((a,b) => a.z - b.z);

// Intenzita radioaktivity (1–5) podle poločasu rozpadu nejstabilnějšího izotopu.
// 1 = velmi slabá (>1 mld. let, primordiální)
// 2 = slabá (1 mil. – 1 mld. let)
// 3 = střední (100 let – 1 mil. let)
// 4 = silná (1 den – 100 let)
// 5 = velmi silná (<1 den)
const RADIOACTIVITY = {
  43:  { intensity: 2, halfLife: "4,2 mil. let",   isotope: "Tc-98"  },
  61:  { intensity: 4, halfLife: "17,7 let",       isotope: "Pm-145" },
  84:  { intensity: 3, halfLife: "124 let",        isotope: "Po-209" },
  85:  { intensity: 5, halfLife: "8,1 hod",        isotope: "At-210" },
  86:  { intensity: 4, halfLife: "3,82 dne",       isotope: "Rn-222" },
  87:  { intensity: 5, halfLife: "22 min",         isotope: "Fr-223" },
  88:  { intensity: 3, halfLife: "1 600 let",      isotope: "Ra-226" },
  89:  { intensity: 4, halfLife: "21,8 let",       isotope: "Ac-227" },
  90:  { intensity: 1, halfLife: "14,05 mld. let", isotope: "Th-232" },
  91:  { intensity: 3, halfLife: "32 760 let",     isotope: "Pa-231" },
  92:  { intensity: 1, halfLife: "4,47 mld. let",  isotope: "U-238"  },
  93:  { intensity: 2, halfLife: "2,14 mil. let",  isotope: "Np-237" },
  94:  { intensity: 2, halfLife: "80,8 mil. let",  isotope: "Pu-244" },
  95:  { intensity: 3, halfLife: "7 370 let",      isotope: "Am-243" },
  96:  { intensity: 2, halfLife: "15,6 mil. let",  isotope: "Cm-247" },
  97:  { intensity: 3, halfLife: "1 380 let",      isotope: "Bk-247" },
  98:  { intensity: 3, halfLife: "900 let",        isotope: "Cf-251" },
  99:  { intensity: 4, halfLife: "471,7 dne",      isotope: "Es-252" },
  100: { intensity: 4, halfLife: "100,5 dne",      isotope: "Fm-257" },
  101: { intensity: 4, halfLife: "51,5 dne",       isotope: "Md-258" },
  102: { intensity: 5, halfLife: "58 min",         isotope: "No-259" },
  103: { intensity: 5, halfLife: "11 hod",         isotope: "Lr-266" },
  104: { intensity: 5, halfLife: "1,3 hod",        isotope: "Rf-267" },
  105: { intensity: 5, halfLife: "16 hod",         isotope: "Db-268" },
  106: { intensity: 5, halfLife: "14 min",         isotope: "Sg-269" },
  107: { intensity: 5, halfLife: "61 s",           isotope: "Bh-270" },
  108: { intensity: 5, halfLife: "9,7 s",          isotope: "Hs-269" },
  109: { intensity: 5, halfLife: "7 s",            isotope: "Mt-278" },
  110: { intensity: 5, halfLife: "11 s",           isotope: "Ds-281" },
  111: { intensity: 5, halfLife: "100 s",          isotope: "Rg-282" },
  112: { intensity: 5, halfLife: "28 s",           isotope: "Cn-285" },
  113: { intensity: 5, halfLife: "9,5 s",          isotope: "Nh-286" },
  114: { intensity: 5, halfLife: "1,9 s",          isotope: "Fl-289" },
  115: { intensity: 5, halfLife: "0,65 s",         isotope: "Mc-290" },
  116: { intensity: 5, halfLife: "53 ms",          isotope: "Lv-293" },
  117: { intensity: 5, halfLife: "51 ms",          isotope: "Ts-294" },
  118: { intensity: 5, halfLife: "0,69 ms",        isotope: "Og-294" },
};

const INTENSITY_LABELS = {
  1: "Velmi slabá",
  2: "Slabá",
  3: "Střední",
  4: "Silná",
  5: "Velmi silná",
};

const INTENSITY_COLORS = {
  1: "#f6d65b",
  2: "#f59f3a",
  3: "#f06f3c",
  4: "#dc4040",
  5: "#a01515",
};
